name: Run pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint pylint-django
      - name: Run pylint
        run: |
          pylint --load-plugins pylint_django \
          --rcfile=.pylintrc \
          --django-settings-module=myproject.settings \ main/ myproject/